logging:
  level:
    com.example.demo: DEBUG

spring:
  h2:
    console:
      enabled: true
      path: /h2/springDemo
  datasource:
    url: jdbc:h2:mem:springDemo
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

rest:
  binlist:
    url: https://lookup.binlist.net/